services:
  - type: web
    name: spring-experiment-docker
    env: docker
    plan: free
    docker:
      dockerfile: Dockerfile
      dockerContext: .
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: JAVA_OPTS
        value: -Xmx512m -Xms256m
      - key: PORT
        value: 8080
    healthCheckPath: /actuator/health
    autoDeploy: true
